version: "3"

services:
  rabbit:
    image: rabbitmq:3
    container_name: rabbit
    ports:
      - "${RABBIT_PORT-15672}:15672"
  presentation-scheduling:
    build:
      context: .
      args:
        PORT: "8001"
    container_name: presentation-scheduling
